"""Update-All Core Library.

Core library providing models, interfaces, and utilities for the update-all system.
"""

from core.config import ConfigManager, YamlConfigLoader, get_config_dir, get_default_config_path
from core.interfaces import ConfigLoader, PluginExecutor, UpdatePlugin
from core.metrics import (
    LatencyTimer,
    MetricLevel,
    MetricsCollector,
    MetricValue,
    PluginMetrics,
    get_metrics_collector,
    set_metrics_collector,
)
from core.models import (
    DownloadEstimate,
    ExecutionResult,
    ExecutionSummary,
    GlobalConfig,
    LogLevel,
    PackageDownload,
    PluginConfig,
    PluginMetadata,
    PluginResult,
    PluginStatus,
    RunResult,
    SystemConfig,
    UpdateCommand,
)
from core.mutex import (
    DeadlockError,
    MutexInfo,
    MutexManager,
    MutexState,
    StandardMutexes,
    WaiterInfo,
)
from core.notifications import (
    NotificationConfig,
    NotificationError,
    NotificationManager,
    NotificationUrgency,
    get_notification_manager,
    load_notification_config,
)
from core.orchestrator import Orchestrator
from core.parallel_orchestrator import ParallelOrchestrator
from core.remote import (
    ConnectionError,
    HostConfig,
    ProgressEvent,
    ProgressEventType,
    RemoteExecutor,
    RemoteUpdateError,
    RemoteUpdateManager,
    RemoteUpdateResult,
    ResilientRemoteExecutor,
)
from core.resource import ResourceContext, ResourceController, ResourceLimits, ResourceUsage
from core.rollback import (
    PluginSnapshot,
    RollbackError,
    RollbackManager,
    RollbackPoint,
    RollbackResult,
    RollbackStatus,
    SnapshotError,
    SnapshotManager,
    SnapshotType,
)
from core.schedule import (
    ScheduleError,
    ScheduleInterval,
    ScheduleManager,
    ScheduleStatus,
    get_schedule_manager,
)
from core.scheduler import ExecutionDAG, PluginNode, Scheduler, SchedulingError
from core.streaming import (
    CompletionEvent,
    EventType,
    OutputEvent,
    Phase,
    PhaseEvent,
    StreamEvent,
    StreamEventQueue,
    batched_stream,
    parse_event,
    parse_progress_line,
    safe_consume_stream,
    timeout_stream,
)
from core.streaming import ProgressEvent as StreamProgressEvent

__version__ = "0.3.0"

__all__ = [
    "CompletionEvent",
    "ConfigLoader",
    "ConfigManager",
    "ConnectionError",
    "DeadlockError",
    "DownloadEstimate",
    "EventType",
    "ExecutionDAG",
    "ExecutionResult",
    "ExecutionSummary",
    "GlobalConfig",
    "HostConfig",
    "LatencyTimer",
    "LogLevel",
    "MetricLevel",
    "MetricValue",
    "MetricsCollector",
    "MutexInfo",
    "MutexManager",
    "MutexState",
    "NotificationConfig",
    "NotificationError",
    "NotificationManager",
    "NotificationUrgency",
    "Orchestrator",
    "OutputEvent",
    "PackageDownload",
    "ParallelOrchestrator",
    "Phase",
    "PhaseEvent",
    "PluginConfig",
    "PluginExecutor",
    "PluginMetadata",
    "PluginMetrics",
    "PluginNode",
    "PluginResult",
    "PluginSnapshot",
    "PluginStatus",
    "ProgressEvent",
    "ProgressEventType",
    "RemoteExecutor",
    "RemoteUpdateError",
    "RemoteUpdateManager",
    "RemoteUpdateResult",
    "ResilientRemoteExecutor",
    "ResourceContext",
    "ResourceController",
    "ResourceLimits",
    "ResourceUsage",
    "RollbackError",
    "RollbackManager",
    "RollbackPoint",
    "RollbackResult",
    "RollbackStatus",
    "RunResult",
    "ScheduleError",
    "ScheduleInterval",
    "ScheduleManager",
    "ScheduleStatus",
    "Scheduler",
    "SchedulingError",
    "SnapshotError",
    "SnapshotManager",
    "SnapshotType",
    "StandardMutexes",
    "StreamEvent",
    "StreamEventQueue",
    "StreamProgressEvent",
    "SystemConfig",
    "UpdateCommand",
    "UpdatePlugin",
    "WaiterInfo",
    "YamlConfigLoader",
    "batched_stream",
    "get_config_dir",
    "get_default_config_path",
    "get_metrics_collector",
    "get_notification_manager",
    "get_schedule_manager",
    "load_notification_config",
    "parse_event",
    "parse_progress_line",
    "safe_consume_stream",
    "set_metrics_collector",
    "timeout_stream",
]
